#-- make sure you update bids_dir and hippunfold opts before running! --
bids_dir: 'bids'  

opts:
  hippunfold: '--modality T1w --output-density 0p5mm 1mm 2mm'

  
#may need to bump this up if you have multiple sessions per subject, try cores=32, mem_mb=128000, time=180 
resources:
  cores: 8
  mem_mb: 32000
  time: 90 

#-- uncomment this section to run on a subset of subjects --
#test_subjects:   
#  - '001'


#-- this usually won't need updating --
bids_subject_match: 'sub-{subject,[a-zA-Z0-9]+}'  #this is just used to identify subject IDs, should not need to modify it


#-- only update below if on a different system than graham --
singularity:
  hippunfold: '/project/6050199/akhanf/singularity/bids-apps/khanlab_hippunfold_v1.2.0.sif'


