bids_subject_match: 'sub-{subject,[a-zA-Z0-9]+}'

bids_dir: 'bids'


#test_subjects:   #uncomment this to run on subset of subjects
#  - '001'

singularity:
  hippunfold: '/project/6050199/akhanf/singularity/bids-apps/khanlab_hippunfold_v1.2.0.sif'

opts:
  hippunfold: '--modality T1w --skip-coreg --skip-preproc --output-density 0p5mm 1mm 2mm --generate-myelin-map'


